name: travel_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  dio: ^5.9.0
  auto_route: ^10.1.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  image_picker: ^1.2.0
  permission_handler: ^12.0.1





  injectable: any
  rxdart: any
dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0
  auto_route_generator: ^10.2.4
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  injectable_generator: ^2.8.1


flutter_gen:
  output: lib/src/shared/assets/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900